# POST http://localhost:3500/admin/newUser/ 
# content-type: application/json

# {
# "email": "john@gmail.com",
# "password": "test2",
# "firstName": "pakao2",
# "lastName": "Doe2",
# "region": "Denver2"
# }

# DELETE http://localhost:3500/admin/users/5cee78500d7d35067041b261
# content-type: application/json

GET http://localhost:3500/admin/users/5cee78500d7d35067041b261 
content-type: application/json