# POST http://localhost:3500/admin/newUser/ 
# content-type: application/json

# {
# "email": "losaSamZatebe@gmail.com",
# "password": "test5",
# "emailPasswrd" : "test4" ,
# "firstName": "Jarni",
# "lastName": "Brzi",
# "region": "Denver5"
# }

# POST http://localhost:3500/admin/users/5cf69001ff8a951fd85f7290
# content-type: application/json

# GET http://localhost:3500/admin/users/5cee78500d7d35097041b261 
# content-type: application/json

# GET http://localhost:3500/admin/newItem 
# content-type: application/json


POST http://localhost:3500/admin/newItem 
content-type: application/json

{
"name": "Test2",
"subCategory": "test2",
"room": "Guest Bathroom",
"price": 5
}